### ISSUE TITLE
Nil pointer exception gongrok.go:162

### ISSUE THREAD

**Issue by DasJott** [revzim/gongrok#1]
If e.g. the path to the ngrok executable is wrong (which I tested intentionally) there is a nil pointer panic.  
It points on line 162 in gongrok.go, where it doesn't check if logging is configured before logging.  
As I didn't initialize logging, the `Logger` is nil at that spot.

I would have made a pull request but then thought that might me too less of a change ;)

**Comment by DasJott** [comment]
Btw: Thank you very much for this nice piece of code. Obviously using it ;)

**Comment by revzim** [comment]
@DasJott sorry for the late response, I've been busy with other projects; however, glad to hear this has been of use.

The oversight of not checking for the binary has been updated. The source now includes a check for the ngrok binary immediately on any init of a new ngrok tunnel client as well as on logger init. Let me know if I broke anything.

**Comment by DasJott** [comment]
Hey! Thank you for fixing.
Yes I really got helped by this library :)

Just updated to newest version and noticed that you now require the ngrok binary to be in a very certain folder.
That is uncomfortable and it was better to have it individually configurable :/

"place binary within your working directory"  - but why? :D

**Comment by DasJott** [comment]
Ah, in your code you do the check for the binary on your delivered settings, not on the given options ;)

Maybe there is something to fix still... I would expect the path from the options I provide to be taken.
