### ISSUE TITLE
Ngrok service in program

### ISSUE THREAD

**Issue by muhammadqazi** [revzim/gongrok#4]
Hello, i am designing an emulator in golang and i need ngrok services in it. I want to start service of go-lang as soon as I call a function with argument port number in it, later i wana use that port for ngrok tunnel, I don't wanna use that localhost:8080/client to provide port host and protocol to program, I hope you get my point, Is it possible ?

**Comment by revzim** [comment]
yes it's possible.

**Comment by muhammadqazi** [comment]
can you explain me a little please
